/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tx_burst_tagger_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8b7855a95dd1bab8d9fd0a326fe7c64e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/rwt_tools/tx_burst_tagger_cc.h>
// pydoc.h is automatically generated in the build directory
#include <tx_burst_tagger_cc_pydoc.h>

void bind_tx_burst_tagger_cc(py::module& m)
{

    using tx_burst_tagger_cc    = ::gr::rwt_tools::tx_burst_tagger_cc;


    py::class_<tx_burst_tagger_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<tx_burst_tagger_cc>>(m, "tx_burst_tagger_cc", D(tx_burst_tagger_cc))

        .def(py::init(&tx_burst_tagger_cc::make),
           py::arg("add_length"),
           py::arg("multiplier"),
           D(tx_burst_tagger_cc,make)
        )
        



        ;




}








