/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(zero_pad.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(22c84a11949b9e348fb8cd2e27682fb0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/rwt_tools/zero_pad.h>
// pydoc.h is automatically generated in the build directory
#include <zero_pad_pydoc.h>

void bind_zero_pad(py::module& m)
{

    using zero_pad    = ::gr::rwt_tools::zero_pad;


    py::class_<zero_pad, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<zero_pad>>(m, "zero_pad", D(zero_pad))

        .def(py::init(&zero_pad::make),
           py::arg("RampUp"),
           py::arg("RampDown"),
           py::arg("PacketSize"),
           D(zero_pad,make)
        )
        



        ;




}








