#ifndef INCLUDED_RWT_TOOLS_COMMON_H
#define INCLUDED_RWT_TOOLS_COMMON_H

// typedef enum {
//     THRESHOLD_DYNAMIC,
//     THRESHOLD_ABSOLUTE,
// } tm_type;

#endif /* INCLUDED_RWT_TOOLS_COMMON_H */
